// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeaderBar: typeof import('./src/components/AppHeaderBar.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseIcon: typeof import('./src/components/BaseIcon.vue')['default']
    BaseInput: typeof import('./src/components/BaseInput.vue')['default']
    BaseSeparator: typeof import('./src/components/BaseSeparator.vue')['default']
    Navigator: typeof import('./src/components/Navigator.vue')['default']
    NavigatorSection: typeof import('./src/components/NavigatorSection.vue')['default']
    ToDo: typeof import('./src/components/ToDo.vue')['default']
    ToDoTools: typeof import('./src/components/ToDoTools.vue')['default']
    ToDoToolsFilter: typeof import('./src/components/ToDoToolsFilter.vue')['default']
  }
}

export { }
