name: E2E Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Build App
        run: npm run build

      - uses: cypress-io/github-action@v2
        with:
          start: npm run preview
          wait-on: "http://localhost:4173"
          browser: chrome
          headless: true
